### ISSUE TITLE
Feature request, show progress on rdrand-gen

### ISSUE THREAD

**Issue by EnriqueVeguer** [jtulak/RdRand#11]
Hi
Could you please add some output for rdrand-gen, so that one can now how many bytes have already written and the speed of the filling?
I'm filling some terabytes luks partitions and I'm not sure if it's slow as /dev/random or it's going fast, if it's like /dev/random it will never finish

Thanks

**Comment by jirka-h** [comment]
Hi,

I recommend using `pv` to report the amount of data and the rate at which data are sent through a pipe. See
https://linux.die.net/man/1/pv

The actual speed will depend on your CPU. Recent CPUs have much slower RDRAND than in the past (by factor 100x or more). On my laptop with Intel Core i7-8650U CPU, I achieve the speed of around 9 MiB/s:

```
$rdrand-gen -t 4 | pv > /dev/null
^C.1MiB 0:00:03 [9.19MiB/s] [    
```

The speed of `/dev/random` depends on the Linux kernel version. I believe since kernel 5.6, there is no significant difference in speed between `/dev/random` and `/dev/urandom`. On my laptop, I achieve speeds of around 37 MiB/s running kernel 5.13. 

```
$pv /dev/random >/dev/null 
^C49MiB 0:00:04 [37.5MiB/s] [ 
```

However, to fill the disk with random data, I would recommend other methods:
1) openssl  - using for example aes-128-ctr mode, you can achieve speeds around 1.8GiB/s
```
openssl enc -e -aes-128-ctr -K $(head -c 16 /dev/random | xxd -p) -iv $(head -c 16 /dev/random | xxd -p) -p -in /dev/zero | pv >/dev/null
^C04GiB 0:00:05 [1.81GiB/s] [                    <=>
```
2)chacha - cryptographically secure RNG. Using for example http://pracrand.sourceforge.net/ implementation, you can achieve speeds of around 407MiB/s
```
$practrand-RNG_output chacha inf | pv >/dev/null 
^C40GiB 0:00:06 [ 407MiB/s] [ 
```
3)Encryption of random data - here aes-128-ctr on top of chacha - 407MiB/s
```
$openssl enc -e -aes-128-ctr -K $(head -c 16 /dev/random | xxd -p) -iv $(head -c 16 /dev/random | xxd -p) -p -in <(practrand-RNG_output chacha inf) | pv > /dev/null 
^C18GiB 0:00:11 [ 403MiB/s] [ 
```

I would recommend going with option #3 - it's fast (probably faster than the maximum write speed of your device) and it provides excellent random data with cryptographic security. 

I hope this helps. Please let me know if you have more questions. 

Jirka

**Comment by jirka-h** [comment]
I'm closing the issue. Please let us know if you have any additional questions.
